services:
  backend-production:
    build: ../backend
    ports:
      - "8001:8000" # Note le port 8001 pour ne pas entrer en conflit
    environment:
      MODEL_NAME: churn-model
      MODEL_STAGE: Production
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_TOKEN: ${MLFLOW_TRACKING_TOKEN}